services:
    ucsf_ldap_orm_entity_manager:
      class: Ucsf\LdapOrmBundle\Doctrine\ORM\EntityManager
      arguments:
        - "%ucsf_ldap_orm%"


parameters:
    ucsf_ldap_orm_test_uri: ldap://ldap.forumsys.com:389
    ucsf_ldap_orm_test_bind_dn: cn=read-only-admin,dc=example,dc=com
    ucsf_ldap_orm_test_password: password
